# kong/config/kong.yaml
_format_version: "3.0"
_transform: true

services:
  - name: kong-admin-api-service
    url: http://kong:8001
    plugins:
      - name: basic-auth
        config:
          hide_credentials: true
    routes:
      - name: kong-admin-api-route
        paths:
          - /admin-api
        strip_path: true

  - name: kong-admin-gui-service
    url: http://kong:8002
    routes:
      - name: kong-admin-gui-route
        paths:
          - /admin-gui
        strip_path: true

consumers:
  - username: kong_manager_admin
    basicauth_credentials:
      - username: kong_manager_admin
        password: YourSecurePasswordForKongManager!

  - username: admin-proxy-user
    basicauth_credentials:
      - username: admin-proxy-user
        password: AnotherSecurePassword