# Template for Python testing workflows
name: Python Test Template

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to test'
        required: true
        type: string
      os:
        description: 'Operating system to test on'
        required: false
        type: string
        default: 'ubuntu-22.04'
      test-path:
        description: 'Path to tests'
        required: false
        type: string
        default: 'tests'
      coverage-threshold:
        description: 'Minimum coverage percentage'
        required: false
        type: number
        default: 80

jobs:
  test:
    name: Test Python ${{ inputs.python-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache dependencies
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.2
        with:
          path: |
            ~/.cache/pip
            ~/Library/Caches/pip
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ inputs.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-xdist

          # Install project dependencies
          for req in $(find . -name "requirements*.txt" -type f); do
            pip install -r "$req" || true
          done
        shell: bash

      - name: Run tests
        run: |
          pytest ${{ inputs.test-path }} \
            --cov \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=${{ inputs.coverage-threshold }} \
            -v
        shell: bash

      - name: Upload coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          file: ./coverage.xml
          flags: unittests
          name: py${{ inputs.python-version }}-${{ inputs.os }}
