---
stream_plugins:
- ip-restriction
- limit-conn
- mqtt-proxy
- syslog
etcd:
  timeout: 30
  host:
  - http://etcd:2379
  watch_timeout: 50
  startup_retry: 2
  prefix: /apisix
  tls:
    verify: true
deployment:
  role_traditional:
    config_provider: etcd
  role: traditional
  etcd:
    timeout: 30
    host:
    - http://etcd:2379
    watch_timeout: 50
    startup_retry: 2
    prefix: /apisix
    tls:
      verify: true
  config_provider: etcd
  admin:
    admin_key_required: true
    admin_api_version: v3
    enable_admin_cors: true
    allow_admin:
    - 0.0.0.0/0
    admin_key:
    - role: admin
      key: dwsDE1OMFwrnrncoChUb3DAEMdpilLCB
      name: admin
    admin_listen:
      port: 9180
      ip: 0.0.0.0
plugin_attr:
  prometheus:
    enable_export_server: true
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: 0.0.0.0  # Change from 127.0.0.1 to 0.0.0.0
      port: 9091
    metric_prefix: apisix_
  skywalking:
    report_interval: 3
    service_instance_name: APISIX Instance Name
    service_name: APISIX
    endpoint_addr: http://127.0.0.1:12800
  inspect:
    delay: 3
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
  server-info:
    report_ttl: 60
  opentelemetry:
    set_ngx_var: false
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16
    collector:
      request_timeout: 3
      request_headers:
        Authorization: token
      address: 127.0.0.1:4318
    resource:
      service.name: APISIX
    trace_id_source: x-request-id
  zipkin:
    set_ngx_var: false
  log-rotate:
    timeout: 10000
    max_size: -1
    interval: 3600
    max_kept: 168
    enable_compression: false
  proxy-mirror:
    timeout:
      connect: 60s
      send: 60s
      read: 60s
  prometheus:
    enable_export_server: true
    export_uri: /apisix/prometheus/metrics
    export_addr:
      port: 9091
      ip: 127.0.0.1
    metric_prefix: apisix_
  dubbo-proxy:
    upstream_multiplex_count: 32
plugins:
- api-breaker
- cors
- fault-injection
- limit-conn
- limit-count
- limit-req
- proxy-cache
- proxy-mirror
- proxy-rewrite
- traffic-split
- basic-auth
- jwt-auth
- key-auth
- openid-connect
- wolf-rbac
- csrf
- ua-restriction
- uri-blocker
- referer-restriction
- http-logger
- skywalking
- zipkin
- opentelemetry
- prometheus
- node-status
- echo
- request-id
- request-validation
- response-rewrite
- grpc-transcode
- grpc-web
- kafka-logger
- syslog
- tcp-logger
- udp-logger
- error-log-logger
- ai-proxy
- ai-prompt-decorator
- ai-prompt-template
- ai-rag
- ai-aws-content-moderation
- ai-prompt-guard
nginx_config:
  event:
    worker_connections: 10620
  main_configuration_snippet: ''
  http_configuration_snippet: ''
  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  http_admin_configuration_snippet: ''
  error_log: logs/error.log
  stream_configuration_snippet: ''
  error_log_level: warn
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  stream:
    access_log: logs/access_stream.log
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time
    access_log_format_escape: default
    lua_shared_dict:
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
      tars-stream: 1m
      etcd-cluster-health-check-stream: 10m
      lrucache-lock-stream: 10m
    enable_access_log: false
  meta:
    lua_shared_dict:
      prometheus-metrics: 15m
  http:
    access_log: logs/access.log
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    access_log_format_escape: default
    client_max_body_size: 0
    send_timeout: 10s
    underscores_in_headers: 'on'
    real_ip_header: X-Real-IP
    real_ip_recursive: 'off'
    real_ip_from:
    - 127.0.0.1
    - 'unix:'
    proxy_ssl_server_name: true
    charset: utf-8
    variables_hash_max_size: 2048
    access_log_buffer: 16384
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    lua_shared_dict:
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
      plugin-ai-rate-limiting: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      plugin-limit-conn: 10m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-req: 10m
      plugin-limit-count: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      prometheus-metrics: 10m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      discovery: 1m
      jwks: 1m
      ocsp-stapling: 10m
      cas-auth: 10m
      tars: 1m
      ext-plugin: 1m
      access-tokens: 1m
      introspection: 10m
    upstream:
      keepalive: 320
      keepalive_requests: 1000
      keepalive_timeout: 60s
    enable_access_log: true
  http_end_configuration_snippet: ''
apisix:
  data_encryption:
    enable_encrypt_fields: true
    keyring:
    - pY3pBRRObol8FTu6
    - VGGH3romXKHvOnHR
  enable_resolv_search_opt: true
  disable_sync_configuration_during_start: false
  node_listen:
  - 9080
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: true
  extra_lua_path: ''
  extra_lua_cpath: ''
  events:
    module: lua-resty-events
  enable_control: true
  ssl:
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
    listen:
    - enable_http3: false
      port: 9443
    enable: true
    ssl_protocols: TLSv1.2 TLSv1.3
  show_upstream_status_in_response_header: false
  enable_admin: true
  normalize_uri_like_servlet: false
  proxy_cache:
    zones:
    - memory_size: 50m
      disk_size: 1G
      disk_path: /tmp/disk_cache_one
      cache_levels: '1:2'
      name: disk_cache_one
    - memory_size: 50m
      name: memory_cache
    cache_ttl: 10s
  proxy_mode: http
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
  enable_server_tokens: true
  resolver_timeout: 5
  enable_http2: true
  delete_uri_tail_slash: false
graphql:
  max_size: 1048576
...
