# This docker-compose.yml is deprecated
# The FastAPI service has been moved to the APISIX stack
# See ../apisix/docker-compose.yml for the integrated configuration

# To start the API:
# cd ../apisix
# docker compose up -d

# The API is accessible through APISIX at:
# http://localhost:9080/api/