services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - apisix_network

  apisix:
    image: apache/apisix:latest
    depends_on:
      - etcd
    ports:
      - "9080:9080"   # HTTP port
      - "9180:9180"   # Admin API port
      - "9091:9091"   # Prometheus metrics port
    volumes:
      - './conf/config.yaml:/usr/local/apisix/conf/config.yaml'
    restart: always
    networks:
      - apisix_network
      - vutf-network
    command: [ "apisix", "start" ]  # Ensure APISIX starts properly

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - './conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    depends_on:
      - apisix
    ports:
      - "9090:9090"   # Prometheus Web UI
    restart: always
    networks:
      - apisix_network

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"   # Grafana Web UI
    restart: always
    networks:
      - apisix_network

  dashboard:
    image: "apache/apisix-dashboard:latest"
    restart: on-failure
    volumes:
      - './conf/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro'
    depends_on:
      - etcd
    ports:
      - "9001:9000/tcp"
    networks:
      - apisix_network

  # ViolentUTF API Service
  fastapi:
    container_name: violentutf_api
    build:
      context: ../violentutf_api/fastapi_app
      dockerfile: Dockerfile
    env_file:
      - ../violentutf_api/fastapi_app/.env
    environment:
      - PYTHONUNBUFFERED=1
      # Override to use internal network names
      - KEYCLOAK_URL=http://keycloak:8080
      - APISIX_BASE_URL=http://apisix:9080
      - APISIX_ADMIN_URL=http://apisix:9180
    volumes:
      - ../violentutf_api/fastapi_app:/app
      - fastapi_data:/app/app_data
      - fastapi_config:/app/config
      - ../violentutf/app_data/violentutf:/app/app_data/violentutf
    networks:
      - apisix_network
      - vutf-network
    depends_on:
      - apisix
      - etcd
    restart: unless-stopped
    # No ports exposed - only accessible through APISIX

networks:
  apisix_network:
    driver: bridge
  vutf-network:
    external: true

volumes:
  fastapi_data:
  fastapi_config:
