version: "3.8"

services:
  apisix:
    # Use a wrapper script to ensure cleanup always happens
    volumes:
      - ./startup-wrapper.sh:/startup-wrapper.sh:ro
    entrypoint: ["/bin/sh", "/startup-wrapper.sh"]

    # Add health check
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9180/apisix/admin/routes",
          "-H",
          "X-API-KEY: ${APISIX_ADMIN_KEY:-dwsDE1OMFwrnrncoChUb3DAEMdpilLCB}",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

    # Add init flag to handle PID 1 issues
    init: true

    # Ensure clean shutdown
    stop_grace_period: 30s

    # Additional environment variables for better behavior
    environment:
      - APISIX_STAND_ALONE=false
      - APISIX_ENABLE_HEARTBEAT=true
