#!/bin/bash
set -e

# DuckDB Recovery Automation Script
# Generated by ViolentUTF Recovery Framework

function log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a /var/log/recovery.log
}

function validate_prerequisites() {
    log_message "Checking prerequisites for DuckDB recovery"

    if [ ! -d "./app_data/violentutf" ]; then
        log_message "WARNING: DuckDB user data directory not found"
        mkdir -p ./app_data/violentutf
    fi

    if [ ! -d "backups/duckdb" ]; then
        log_message "WARNING: DuckDB backup directory not found"
        mkdir -p backups/duckdb
    fi

    log_message "Prerequisites check completed"
}

function identify_affected_users() {
    log_message "Identifying affected user databases"

    AFFECTED_DBS=$(find ./app_data/violentutf -name "pyrit_memory_*.db" -type f)
    if [ -z "$AFFECTED_DBS" ]; then
        log_message "No user databases found"
        return 0
    fi

    for db in $AFFECTED_DBS; do
        username=$(basename "$db" .db | sed 's/pyrit_memory_//')
        log_message "Found user database: $username"
    done
}

function backup_user_databases() {
    log_message "Backing up user databases"

    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    mkdir -p "backups/duckdb/corrupted_${TIMESTAMP}"

    find ./app_data/violentutf -name "pyrit_memory_*.db" -type f -exec cp {} "backups/duckdb/corrupted_${TIMESTAMP}/" \;
}

function recreate_user_databases() {
    log_message "Recreating user databases"

    python3 -c "
import glob
import os
from pathlib import Path

# Import DuckDBManager if available
try:
    from violentutf_api.fastapi_app.app.db.duckdb_manager import DuckDBManager

    for db_file in glob.glob('./app_data/violentutf/pyrit_memory_*.db'):
        username = Path(db_file).stem.replace('pyrit_memory_', '')
        print(f'Recreating database for user: {username}')

        # Remove corrupted database
        os.remove(db_file)

        # Create new clean database
        manager = DuckDBManager(username)
        print(f'Created clean database for {username}')

except ImportError:
    print('DuckDBManager not available - using fallback method')
    import duckdb

    for db_file in glob.glob('./app_data/violentutf/pyrit_memory_*.db'):
        username = Path(db_file).stem.replace('pyrit_memory_', '')
        print(f'Recreating database for user: {username}')

        # Remove corrupted database
        os.remove(db_file)

        # Create new database with basic schema
        conn = duckdb.connect(db_file)
        conn.execute('CREATE TABLE generators (id INTEGER, name TEXT, config TEXT)')
        conn.execute('CREATE TABLE datasets (id INTEGER, name TEXT, path TEXT)')
        conn.close()
        print(f'Created basic database for {username}')
"
}

function notify_users() {
    log_message "Notifying affected users"

    python3 scripts/recovery-management/notify_users.py --service duckdb --status recovered
}

function cleanup() {
    log_message "Performing cleanup tasks"
    # Remove temporary files if any
}

function main() {
    log_message "Starting DuckDB recovery procedure"

    validate_prerequisites
    identify_affected_users
    backup_user_databases
    recreate_user_databases
    notify_users

    log_message "DuckDB recovery completed successfully"
    cleanup
}

# Trap for cleanup on exit
trap cleanup EXIT

main "$@"
