#!/bin/bash
set -e

# PostgreSQL Recovery Automation Script
# Generated by ViolentUTF Recovery Framework

function log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a /var/log/recovery.log
}

function validate_prerequisites() {
    log_message "Checking prerequisites for PostgreSQL recovery"

    # Check if Docker is running
    if ! docker ps >/dev/null 2>&1; then
        log_message "ERROR: Docker is not running"
        exit 1
    fi

    # Check if backup directory exists
    if [ ! -d "backups/postgresql" ]; then
        log_message "WARNING: PostgreSQL backup directory not found"
        mkdir -p backups/postgresql
    fi

    log_message "Prerequisites check completed"
}

function stop_services() {
    log_message "Stopping Keycloak services"
    docker-compose -f keycloak/docker-compose.yml down || true
    sleep 5
}

function restore_database() {
    log_message "Restoring PostgreSQL database from backup"

    LATEST_BACKUP=$(ls -t backups/postgresql/*.sql 2>/dev/null | head -1)
    if [ -z "$LATEST_BACKUP" ]; then
        log_message "ERROR: No PostgreSQL backup found"
        exit 1
    fi

    log_message "Using backup: $LATEST_BACKUP"

    # Start PostgreSQL container if not running
    docker-compose -f keycloak/docker-compose.yml up -d postgres
    sleep 10

    # Restore database
    docker exec -i keycloak-postgres psql -U keycloak -d postgres -c "DROP DATABASE IF EXISTS keycloak;"
    docker exec -i keycloak-postgres psql -U keycloak -d postgres -c "CREATE DATABASE keycloak;"
    docker exec -i keycloak-postgres psql -U keycloak -d keycloak < "$LATEST_BACKUP"

    log_message "Database restoration completed"
}

function start_services() {
    log_message "Starting Keycloak services"
    docker-compose -f keycloak/docker-compose.yml up -d
    sleep 15
}

function validate_recovery() {
    log_message "Validating PostgreSQL recovery"

    # Check PostgreSQL connection
    if ! pg_isready -h localhost -p 5432 -U keycloak >/dev/null 2>&1; then
        log_message "ERROR: PostgreSQL is not ready"
        return 1
    fi

    # Check Keycloak endpoint
    if ! curl -f -s http://localhost:8080/auth/realms/violentutf >/dev/null; then
        log_message "ERROR: Keycloak endpoint not responding"
        return 1
    fi

    log_message "Recovery validation successful"
    return 0
}

function cleanup() {
    log_message "Performing cleanup tasks"
    # Remove temporary files, reset permissions, etc.
}

function main() {
    log_message "Starting PostgreSQL recovery procedure"

    validate_prerequisites
    stop_services
    restore_database
    start_services

    if validate_recovery; then
        log_message "PostgreSQL recovery completed successfully"
        cleanup
        exit 0
    else
        log_message "PostgreSQL recovery validation failed"
        cleanup
        exit 1
    fi
}

# Trap for cleanup on exit
trap cleanup EXIT

main "$@"
