#!/bin/bash
set -e

# SQLite Recovery Automation Script
# Generated by ViolentUTF Recovery Framework

function log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a /var/log/recovery.log
}

function validate_prerequisites() {
    log_message "Checking prerequisites for SQLite recovery"

    if [ ! -f "violentutf_api/fastapi_app/app_database.db" ]; then
        log_message "WARNING: SQLite database file not found"
    fi

    if [ ! -d "backups/sqlite" ]; then
        log_message "WARNING: SQLite backup directory not found"
        mkdir -p backups/sqlite
    fi
}

function stop_services() {
    log_message "Stopping FastAPI services"
    docker-compose -f violentutf_api/docker-compose.yml down || true
}

function backup_corrupted_database() {
    log_message "Backing up corrupted database"

    if [ -f "violentutf_api/fastapi_app/app_database.db" ]; then
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        cp violentutf_api/fastapi_app/app_database.db "backups/sqlite/corrupted_${TIMESTAMP}.db"
    fi
}

function attempt_repair() {
    log_message "Attempting SQLite database repair"

    if sqlite3 violentutf_api/fastapi_app/app_database.db ".recover" > /tmp/recovered.sql 2>/dev/null; then
        sqlite3 violentutf_api/fastapi_app/app_database_repaired.db < /tmp/recovered.sql

        if sqlite3 violentutf_api/fastapi_app/app_database_repaired.db "PRAGMA integrity_check" | grep -q "ok"; then
            mv violentutf_api/fastapi_app/app_database_repaired.db violentutf_api/fastapi_app/app_database.db
            log_message "Database repair successful"
            return 0
        fi
    fi

    log_message "Database repair failed"
    return 1
}

function restore_from_backup() {
    log_message "Restoring SQLite from backup"

    LATEST_BACKUP=$(ls -t backups/sqlite/*.db 2>/dev/null | grep -v corrupted | head -1)
    if [ -z "$LATEST_BACKUP" ]; then
        log_message "ERROR: No SQLite backup found"
        return 1
    fi

    cp "$LATEST_BACKUP" violentutf_api/fastapi_app/app_database.db
    log_message "Restored from backup: $LATEST_BACKUP"
    return 0
}

function start_services() {
    log_message "Starting FastAPI services"
    docker-compose -f violentutf_api/docker-compose.yml up -d
    sleep 10
}

function validate_recovery() {
    log_message "Validating SQLite recovery"

    # Check database integrity
    if ! sqlite3 violentutf_api/fastapi_app/app_database.db "PRAGMA integrity_check" | grep -q "ok"; then
        log_message "ERROR: Database integrity check failed"
        return 1
    fi

    # Check API health
    if ! curl -f -s http://localhost:9080/health >/dev/null; then
        log_message "ERROR: API health check failed"
        return 1
    fi

    log_message "Recovery validation successful"
    return 0
}

function cleanup() {
    log_message "Performing cleanup tasks"
    rm -f /tmp/recovered.sql
    rm -f violentutf_api/fastapi_app/app_database_repaired.db
}

function main() {
    log_message "Starting SQLite recovery procedure"

    validate_prerequisites
    stop_services
    backup_corrupted_database

    if ! attempt_repair; then
        if ! restore_from_backup; then
            log_message "ERROR: Both repair and backup restoration failed"
            cleanup
            exit 1
        fi
    fi

    start_services

    if validate_recovery; then
        log_message "SQLite recovery completed successfully"
        cleanup
        exit 0
    else
        log_message "SQLite recovery validation failed"
        cleanup
        exit 1
    fi
}

# Trap for cleanup on exit
trap cleanup EXIT

main "$@"
