#!/bin/bash
# Setup fast pre-commit for GitHub Desktop

echo "🚀 Setting up fast pre-commit for GitHub Desktop..."

# Install fast pre-commit hooks
pre-commit install --config .pre-commit-config-fast.yaml

# Create symlink for GitHub Desktop to use fast config
if [ -f .git/hooks/pre-commit ]; then
    echo "📝 Backing up current pre-commit hook..."
    cp .git/hooks/pre-commit .git/hooks/pre-commit.full.backup
fi

# Create fast pre-commit script
cat > .git/hooks/pre-commit << 'EOF'
#!/usr/bin/env bash
# Fast pre-commit hook for GitHub Desktop
# Generated by setup_fast_precommit.sh

INSTALL_PYTHON=/Library/Frameworks/Python.framework/Versions/3.12/bin/python3
ARGS=(hook-impl --config=.pre-commit-config-fast.yaml --hook-type=pre-commit)

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
EOF

chmod +x .git/hooks/pre-commit

echo "✅ Fast pre-commit configured for GitHub Desktop!"
echo ""
echo "📊 Hook count comparison:"
echo "  Full config: ~25 hooks (slow)"
echo "  Fast config: ~10 hooks (fast)"
echo ""
echo "🔄 To switch back to full pre-commit:"
echo "  pre-commit install  # (uses default .pre-commit-config.yaml)"
echo ""
echo "🧪 To test fast pre-commit:"
echo "  pre-commit run --config .pre-commit-config-fast.yaml --all-files"
