# Branding and styling configuration for ViolentUTF reports
# This file defines visual appearance, corporate branding, and styling options

branding:
  # Company Information
  company_name: ""
  company_logo_url: ""
  company_website: ""
  report_title_prefix: "ViolentUTF Security Assessment"

  # Security Classifications
  classification_levels:
    - "UNCLASSIFIED"
    - "INTERNAL USE"
    - "CONFIDENTIAL"
    - "RESTRICTED"
  default_classification: "INTERNAL USE"

  # Contact Information
  contact_info:
    security_team_email: ""
    report_prepared_by: "ViolentUTF AI Red Team Platform"

# Visual Styling Configuration
styling:
  # Color Schemes
  color_schemes:
    professional:
      primary: "#007acc"
      secondary: "#005a99"
      success: "#32CD32"
      warning: "#FFD700"
      danger: "#DC143C"
      critical: "#8B0000"
      background: "#f5f5f5"
      text: "#333333"

    corporate:
      primary: "#2c3e50"
      secondary: "#34495e"
      success: "#27ae60"
      warning: "#f39c12"
      danger: "#e74c3c"
      critical: "#c0392b"
      background: "#ecf0f1"
      text: "#2c3e50"

    security:
      primary: "#000080"
      secondary: "#4169E1"
      success: "#008000"
      warning: "#FFA500"
      danger: "#FF0000"
      critical: "#800000"
      background: "#F0F0F0"
      text: "#000000"

  # Typography
  fonts:
    primary_font: "Arial, sans-serif"
    heading_font: "Arial Black, sans-serif"
    monospace_font: "Courier New, monospace"
    font_sizes:
      h1: "2.5rem"
      h2: "2rem"
      h3: "1.5rem"
      body: "1rem"
      small: "0.875rem"

  # Layout Configuration
  layout:
    max_width: "1200px"
    margin: "20px"
    padding: "30px"
    border_radius: "8px"
    box_shadow: "0 2px 10px rgba(0,0,0,0.1)"

  # Chart Styling
  charts:
    default_theme: "plotly_white"
    color_palette:
      - "#1f77b4"
      - "#ff7f0e"
      - "#2ca02c"
      - "#d62728"
      - "#9467bd"
      - "#8c564b"
      - "#e377c2"
      - "#7f7f7f"
      - "#bcbd22"
      - "#17becf"
    font_family: "Arial"
    background_color: "white"

# Header Configuration
header:
  show_logo: true
  logo_position: "left"  # left, right, center
  logo_max_height: "60px"
  show_company_name: true
  show_report_title: true
  show_generation_date: true
  show_classification: true

  # Header styling
  header_background: "linear-gradient(135deg, #007acc 0%, #005a99 100%)"
  header_text_color: "white"
  border_bottom: "3px solid #007acc"

# Footer Configuration
footer:
  show_footer: true
  content: "Generated by ViolentUTF - AI Red Teaming Platform"
  show_page_numbers: true
  show_timestamp: true

  # Footer styling
  border_top: "1px solid #ddd"
  background_color: "#f8f9fa"
  text_color: "#6c757d"

# Table Styling
tables:
  stripe_rows: true
  border_style: "1px solid #dee2e6"
  header_background: "#f8f9fa"
  header_text_color: "#495057"
  hover_color: "#f5f5f5"

# Severity Level Styling
severity_styling:
  critical:
    color: "#8B0000"
    background: "#ffe6e6"
    font_weight: "bold"
    icon: "⚠️"

  high:
    color: "#DC143C"
    background: "#ffe6e6"
    font_weight: "bold"
    icon: "🔴"

  medium:
    color: "#FF8C00"
    background: "#fff3e0"
    font_weight: "normal"
    icon: "🟠"

  low:
    color: "#FFD700"
    background: "#fffbf0"
    font_weight: "normal"
    icon: "🟡"

  minimal:
    color: "#32CD32"
    background: "#f0fff0"
    font_weight: "normal"
    icon: "🟢"

  unknown:
    color: "#808080"
    background: "#f8f9fa"
    font_weight: "normal"
    icon: "❓"

# Custom CSS Classes
custom_css:
  container: |
    .report-container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      font-family: Arial, sans-serif;
      line-height: 1.6;
    }

  metrics: |
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin: 20px 0;
    }
    .metric-card {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #007acc;
    }
    .metric-value {
      font-size: 2rem;
      font-weight: bold;
      color: #007acc;
    }

  tables: |
    .data-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    .data-table th, .data-table td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    .data-table th {
      background-color: #f8f9fa;
      font-weight: bold;
    }
    .data-table tr:hover {
      background-color: #f5f5f5;
    }
